# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en,el

pipeline:
- name: SpacyNLP
  model: en_core_web_md
- name: SpacyTokenizer
- name: RegexFeaturizer
  case_sensitive: false
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "rasa/LaBSE"
  cache_dir: ./.cache
- name: SpacyFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 141
  model_confidence: softmax
  loss_type: cross_entropy
  constrain_similarities: true
  number_of_transformer_layers: 2
  number_of_attention_heads: 4
  batch_size:
  - 64
  - 128
  # evaluate_on_number_of_examples: 200
  # evaluate_every_number_of_epochs: 5
  # regularization_constant: 0.002
  random_seed: 1
  tensorboard_log_directory: ./.tensorboard/DIET
  tensorboard_log_level: epoch
  checkpoint_model: true
- name: RegexEntityExtractor
  case_sensitive: false
  use_lookup_tables: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 26
  model_confidence: softmax
  loss_type: cross_entropy
  constrain_similarities: true
  regularization_constant: 0.002
  random_seed: 1
  batch_size:
  - 64
  - 128
  # evaluate_on_number_of_examples: 5
  # evaluate_every_number_of_epochs: 1
  # tensorboard_log_directory: ./.tensorboard/DIET2BOW
  # tensorboard_log_level: epoch
  checkpoint_model: true
- name: FallbackClassifier
  threshold: 0.8
  ambiguity_threshold: 0.1

#pipeline:
## We keep the default rasa pipeline but just change the threshold for the fallback intent from 0.3 -> 0.8
#
#- name: WhitespaceTokenizer
#- name: RegexFeaturizer
#- name: LexicalSyntacticFeaturizer
#- name: CountVectorsFeaturizer
#- name: CountVectorsFeaturizer
#  analyzer: char_wb
#  min_ngram: 1
#  max_ngram: 4
#- name: DIETClassifier
#  epochs: 100
#  constrain_similarities: true
#- name: EntitySynonymMapper
#- name: ResponseSelector
#  epochs: 100
#  constrain_similarities: true
#- name: FallbackClassifier
#     # This is the default
#  threshold: 0.8
#  ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: UnexpecTEDIntentPolicy
     max_history: 5
     epochs: 100
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
assistant_id: 20231026-162535-daring-watchtower
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
